version: '3.7'
services:
    db:
        image: mongo:latest
        container_name: 'shopping-online-mongodb'
        volumes:
            - mongodb-volume:/data/db
        ports:
            - '50000:27017'  
    mongodb-api-server:
        build: ./
        container_name: 'shopping-online-mongodb-api-server'
        ports:
            - '50001:3000'
        volumes:
            - ./node_modules:/usr/src/app/node_modules
            - ./src:/usr/src/app/src
        depends_on: 
            - db
volumes:    
    mongodb-volume: